repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-json
    -   id: check-ast

-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.4'
    hooks:
    -   id: flake8
